// `.env.ts` is generated by the `npm run env` command
import {env} from './.env';

export const environment = {
  production: true,
  version: '1.0.0',
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  // socketServer:'http://n4.iworklab.com:4013'
  socketServer: 'http://bitorocoin.com:4013'           // CLient Server
};
